apiVersion: v1
kind: ServiceAccount
metadata:
  name: metric-collector-sa
  namespace: tbot-monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metric-collector
  namespace: tbot-monitoring
  labels:
    app: metric-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metric-collector
  template:
    metadata:
      labels:
        app: metric-collector
    spec:
      serviceAccountName: metric-collector-sa
      nodeSelector:
        kubernetes.io/arch: amd64     
      containers:
      - name: collector
        image: ketidevit2/sdi-metric-collector:1.0.0  
        env:
          # ─── RabbitMQ 접속 정보 ─────────────────────────
          - name: RABBITMQ_HOST
            value: rabbitmq.tbot-monitoring.svc.cluster.local
          - name: RABBITMQ_USER
            valueFrom:
              secretKeyRef:
                name: rabbitmq-creds
                key: user
          - name: RABBITMQ_PASS
            valueFrom:
              secretKeyRef:
                name: rabbitmq-creds
                key: pass
          - name: RABBITMQ_QUEUE
            value: node.metrics
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
