---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: sdi-demo
  name: male-controller-manager-rolebinding-sdi-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: male-controller-manager-role-sdi-demo
subjects:
- kind: ServiceAccount
  name: male-controller-controller-manager
  namespace: male-controller-system