---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: male-controller-system
  name: male-controller-malepolicy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: male-controller-malepolicy-role
subjects:
- kind: ServiceAccount
  name: male-controller-controller-manager
  namespace: male-controller-system